### ISSUE TITLE
Expand data into a representation suitable for manipulation in the frontend upon load

### ISSUE THREAD

**Issue by aklt** [solsort/mobibl#36]
This should be a handler running as the first thing when the app is loaded and when additional data is received form the network.

This could be done with the sample data, but I think it is better to have sample data be redundant
and wait until there is more clarity about what actual data looks like.

**Comment by rasmuserik** [comment]
Instead of redundant data, it might make sense to just have the work-id, and then find the metadata from the `:works` section of the application database?

**Comment by aklt** [comment]
Ah, yes I can see that is the proper way.  I will have a look at that later tomorrow.
