### ISSUE TITLE
switch to semantic-ui

### ISSUE THREAD

**Issue by rasmuserik** [solsort/mobibl#60]
Looking further into css-frameworks, semantic-ui looks better.

**Comment by rasmuserik** [comment]
Actually duplicate of part of #55

**Comment by aklt** [comment]
I have been looking at semantic ui and found that it requires jQuery which I think is
problematic since jQuery is huge and slow.   See this issue: 

    https://github.com/Semantic-Org/Semantic-UI/issues/1175

OTOH, it may be that we can rely on parts of it that are not dependent on jQuery.

**Comment by rasmuserik** [comment]
Yes, I agree it would be best with a CSS-framework that did not depend on
jQuery.
But the major ones (bootstrap, foundation, semantic-ui) all seem to need
it.

Do you have a suggestion for a mature alternative?
Otherwise we could also just bite the bullet and use this semantic-ui for
now,
- maybe look into not using the parts that depend on jQuery.

On the long term it would be nice to have something in clojurescript,
a la re-com, but with mobile support.

On Fri, Apr 8, 2016 at 11:37 AM, Anders Thøgersen <notifications@github.com>
wrote:

> I have been looking at semantic ui and found that it requires jQuery which
> I think is
> problematic since jQuery is huge and slow. See this issue:
>
> https://github.com/Semantic-Org/Semantic-UI/issues/1175
>
> OTOH, it may be that we can rely on parts of it that are not dependent on
> jQuery.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/solsort/mobibl/issues/60#issuecomment-207349770>
>



-- 
RasmusErik Voel Jensen
Independent computer scientist and software developer
more info on https://solsort.com

**Comment by jacobandresen** [comment]
How about using a preprocessor?  I like the sass and susy combination. jquery is becoming obsolete these days.

**Comment by rasmuserik** [comment]
It turns out that semantic-ui works quite well, also without javascript/jquery.

The problem it needs to solve is to quickly get some usable components, - and while sass/susy is more flexible, I think semantic-ui solves this better.
